version: 2.1

machine:
  services:
    - docker
  python:
    version: 3.8.5

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout

      # Setting up the environment necessary for identiDoc to run
      - run:
          name: Create virtual environment
          command: |
            . setup_env.sh

      - run:
          # TODO - Generate coverage reports and run all future unit tests
          name: Run unit tests
          command: |
            . identidoc_venv/bin/activate
            coverage run -m unittest discover
            coverage html
      - store_artifacts:
          path: htmlcov/*


# Orchestrate our job run sequence
workflows:
  Build and Test:
    jobs:
      - build
      