version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run: mkdir test_reports
      - run:
          name: Create virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            export PYTHONPATH=${VIRTUAL_ENV}/../
            pip install -r ./requirements/requirements.txt


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      